### ISSUE TITLE
Error when upgrading from v1.0.5 to v1.0.6

### ISSUE THREAD

**Issue by franrios** [evollu/react-native-firebase-analytics#36]
When installing latest version I get the following error. I've installed manually **v1.0.5** to avoid this error  for now .

```
/projectDir/node_modules/react-native-firebase-analytics/android/src/main/java/com/evollu/react/fa/FIRAnalyticsModule.java:50: error: cannot find symbol
            FirebaseAnalytics.getInstance(getReactApplicationContext()).setCurrentScreen(currentActivity, name, null);
                                                                       ^
  symbol:   method setCurrentScreen(Activity,String,<null>)
  location: class FirebaseAnalytics
1 error
:react-native-firebase-analytics:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```

**Comment by avkvak** [comment]
+1 Same issue

**Comment by mikemonteith** [comment]
This might be an issue with your firebase package being out of date?
`setCurrentScreen` was only added with v9.8 on Oct 24th https://firebase.google.com/support/release-notes/android

**Comment by bitcoinvsalts** [comment]
+1 any solution for this issue?

**Comment by evollu** [comment]
yes update your firebase package

**Comment by KendraTang** [comment]
I updated Android Studio to 2.2.1 and then issue solved.
